### ISSUE TITLE
Paddlespeech error: AttributeError: can't set attribute

### ISSUE THREAD

**Issue by Hyfred** [wechaty/python-wechaty-plugin-contrib#17]
python-wechaty-plugin-contrib % python paddlespeech-bot.py         

```shell
2022-07-23 10:23:33,273 - WechatyPuppet.Schema.Base - WARNING - invalid fields: <['endpoint', 'token']> to initialize type<<class 'wechaty_puppet.schemas.puppet.PuppetOptions'>> which are should not be here, we suggest that you should post an issue to python-wechaty to fix this issue 
you should give these infos: 
* the version of wechaty: 			0.8.63
* the version of wechaty_puppet: 		0.4.21
* the version of wechaty_puppet_service: 	0.8.10
* the token type: <unkonwn> token 

/Users/liuhongye/Software/anaconda3/envs/drugdiscovery/lib/python3.7/site-packages/pyee/__init__.py:67: DeprecationWarning: pyee.AsyncIOEventEmitter has been moved to the pyee.asyncio module.
  "pyee.AsyncIOEventEmitter has been moved to the pyee.asyncio "
Traceback (most recent call last):
  File "paddlespeech-bot.py", line 27, in <module>
    asyncio.run(run())
  File "/Users/liuhongye/Software/anaconda3/envs/drugdiscovery/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/liuhongye/Software/anaconda3/envs/drugdiscovery/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "paddlespeech-bot.py", line 23, in run
    plugin = PaddleSpeechPlugin()
  File "/Users/liuhongye/UU/wechaty/python-wechaty-plugin-contrib/src/wechaty_plugin_contrib/contrib/paddlespeech_plugin/plugin.py", line 17, in __init__
    self.cache_dir = f'.wechaty/{self.name}'
AttributeError: can't set attribute
```

**Comment by wj-Mcat** [comment]
You can upgrade the wechaty package to fix this issue.
